name: yj-proj
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
    - torch==2.1.0
    - transformers==4.42.4
    - accelerate==0.33.0
    - peft==0.10.0
    - datasets==2.20.0
    - sentencepiece>=0.1.99
    - lm-eval==0.3.0
    - nevergrad>=0.11.0
    - k-means-constrained
    - scikit-learn
    - numpy==1.26.4
    - pandas
    - tqdm
    - seaborn
    - matplotlib
    - safetensors
    - einops
    - protobuf
    - fuzzywuzzy
    - python-Levenshtein
    - rouge
    - rouge-score
    - jieba
